INSERT INTO categories (name, description)
VALUES
("Digital & Mixed Signal", ""),
("Analog", ""),
("Mixed Signal", ""),
("Opto´s", ""),
("Discrete", ""),
("Modules", ""),
("Passive", ""),
("Connector´s", "");


INSERT INTO categories (name, parent_id)
VALUES
("Logic TTL/CMOS", 1),
("Memory", 1),
("Microcontroller", 1),
("Microprozessor", 1),
("Peripherie", 1),
("OP-AMP's", 2),
("Comparator", 2),
("Analog Switches", 2),
("Voltage Regulator", 2),
("References", 2),
("Switch Converter", 2),
("Pump Charge", 2),
("Battery Charger", 2),
("Solar Power", 2),
("Temperature Sensores", 2),
("Hall Sensores", 2),
("Special Function", 2),
("Power Driver", 2),
("V/F-Converter", 3),
("DAC´s", 3),
("ADC´s", 3),
("Function Generator", 3),
("Capacitive Sensor´s", 3),
("Current Sensors´s", 3),
("Transmitter/Receiver", 3),
("Isolator´s", 3),
("Optocoupler", 4),
("Encoder", 4),
("LED´s ", 4),
("7-Segment Displays", 4),
("LCD-Display", 4),
("FET / MOSFET Transistor", 5),
("Bipolar Power Transistor", 5),
("Bipolar Medium Power Transistor", 5),
("Bipolar Small Power Transistor", 5),
("IGBT´s", 5),
("Triac´s", 5),
("Thyristor´s", 5),
("Bridge Rectifier´s", 5),
("Small Signal Diode´s", 5),
("Small Signal Diode´s", 5),
("Zener", 5),
("Capacitors leaded", 7),
("Capacitors leaded Tantal", 7),
("Capacitors Trimmer", 7),
("Capacitors SMD", 7),
("Capacitors SMD Tantal", 7),
("Capacitors Tantal", 7),
("ESD Suppresor", 7),
("Crystals", 7),
("Inductors", 7),
("Resistors leaded", 7),
("Resistors SMD", 7),
("Termistores", 7),
("Trimmpot Multiturn", 7),
("Trimmpot Singleturn", 7),
("Precision Pot's 10G", 7),
("Standard Pot's 270º", 7),
("Board Connector´s", 8),
("Header", 8),
("Cable Connector´s", 8),
("Through Hole", 67),
("SMD", 67);

